export default [
    {
      menu:'工作台',
      permissionCode:'workDock_lookUp',
      defaultDock:true,
      icon:'&#xe606;',
      subMenu:[
        {
          menu:'默认工作台',
          route:'/Home',
          permissionCode:'Home'
        }
      ]
    },
    {
      menu:'企业管理',
      permissionCode:'enterprise',
      icon:'&#xe600;',
      subMenu:[
        {
          menu:'企业管理',
          route:'/Company',
          permissionCode:'enterprise_lookup'
        }
      ]
    },
    {
      menu:'组织机构',
      permissionCode:'organization',
      icon:'&#xe62e;',
      subMenu:[
        {
          menu:'组织机构',
          route:'/Organization',
          permissionCode:'organize_lookup'
        }
      ]
    },
    {
      menu:'员工管理',
      permissionCode:'personnel"',
      icon:'&#xe68d;',
      subMenu:[
        {
          menu:'员工管理',
          route:'/Personnel',
          permissionCode:'employee_lookup'
        }
      ]
    },
    {
      menu:'设备管理',
      permissionCode:'device',
      icon:'&#xe61c;',
      subMenu:[
        {
          menu:'设备管理',
          route:'/Equipment',
          permissionCode:'device_lookup'
        },
        {
          menu:'类别管理',
          route:'/Category',
          permissionCode:'deviceCate_lookup'
        }
      ]
    },
    {
      menu:'设备监控',
      permissionCode:'monit',
      icon:'&#xe6a0;',
      subMenu:[
        {
          menu:'设备实时状态',
          route:'/Monit',
          permissionCode:'deviceState_lookup'
        },
        {
          menu:'设备OEE分析',
          route:'/Oee',
          permissionCode:'deviceOEE_lookup'
        }
      ]
    },
    {
      menu:'运维管理',
      permissionCode:'ops',
      icon:'&#xe73a;',
      subMenu:[
        {
          menu:'设备故障',
          route:'/Breakdown',
          permissionCode:'fault_lookup'
        },
        {
          menu:'检修计划',
          route:'/TurnaroundPlans',
          permissionCode:'overhaul_lookup'
        },
        {
          menu:'保养计划',
          route:'/Upkeep',
          permissionCode:'maintain_lookup'
        }
      ]
    },
    {
      menu:'备品备件',
      permissionCode:'partInfo',
      icon:'&#xe690;',
      subMenu:[
        {
          menu:'备件基础信息',
          route:'/SparePart',
          permissionCode:'partInfo_lookup'
        },
        {
          menu:'备件分类',
          route:'/SparePartsClassification',
          permissionCode:'partCate_lookup'
        },
        {
          menu:'备件入库',
          route:'/SparePartsWarehouse',
          permissionCode:'partWarehouse_lookup'
        },
        {
          menu:'入库明细',
          route:'/WarehousingDetail',
          permissionCode:'partWarehouseInfo_lookup'
        }
      ]
    },
    {
      menu:'工单系统',
      permissionCode:'workOrder',
      icon:'&#xe60b;',
      subMenu:[
        {
          menu:'工单列表',
          route:'/WorkOrder',
          permissionCode:'work_lookup'
        }
      ]
    },
    {
      menu:'消息管理',
      permissionCode:'msg',
      icon:'&#xe627;',
      subMenu:[
        {
          menu:'消息管理',
          route:'/Message',
          permissionCode:'message_lookup'
        }
      ]
    },
    {
      menu:'角色管理',
      permissionCode:'role',
      icon:'&#xe630;',
      subMenu:[
        {
          menu:'角色管理',
          route:'/RoleManagement',
          permissionCode:'role_lookup'
        }
      ]
    },
    {
      menu:'系统管理',
      permissionCode:'sys',
      icon:'&#xe60a;',
      subMenu:[
        {
          menu:'用户管理',
          route:'/User',
          permissionCode:'user_lookup'
        }
      ]
    }
  ]