<template>
  <div
    class="register"
    v-show="ishide"
  >
    <div v-show="backshow">
      <h2>企业注册</h2>
      <div class="titleText">（企业注册信息填写）</div>
      <el-form
        :label-position="labelPosition"
        label-width="160px"
        :model="company"
        :rules="registerRules"
        ref="company"
      >
        <el-form-item
          label="企业名称："
          prop="name"
        >
          <el-input
            placeholder="营业执照主体单位名称"
            size="small"
            v-model="company.name"
            style="width:80%"
          ></el-input>
        </el-form-item>
        <el-form-item
          label="法人代表："
          prop="corporation"
        >
          <el-input
            placeholder="营业执照法定代表人"
            size="small"
            v-model="company.corporation"
            style="width:80%"
          ></el-input>
        </el-form-item>
        <el-form-item
          label="联系电话："
          prop="phone"
        >
          <el-input
            placeholder="如：028-XXXXXXXX"
            size="small"
            v-model="company.phone"
            style="width:80%"
          ></el-input>
        </el-form-item>
        <el-form-item
          label="企业地址："
          prop="address"
        >
          <el-input
            placeholder="企业现在所处的详细地址"
            size="small"
            v-model="company.address"
            style="width:80%"
          ></el-input>
        </el-form-item>
        <el-form-item
          label="统一社会信用代码："
          prop="companyID"
        >
          <el-input
            placeholder="18位统一社会信用代码"
            size="small"
            v-model="company.companyID"
            style="width:80%"
          ></el-input>
        </el-form-item>
        <el-form-item
          label="营业执照："
          props="dialogImageUrl"
          style="padding-top: 6px;"
        >
          <el-upload
            style="display:inline-block;vertical-align:top"
            :action="uploadUrl()"
            accept="image/jpeg,image/png"
            list-type="picture-card"
            :limit="1"
            :on-success="handleAvatarSuccess"
            :before-upload="beforeAvatarUpload"
            :on-preview="handlePictureCardPreview"
            :on-remove="handleRemove"
          >
            <i class="el-icon-plus"></i>
          </el-upload>
          <el-dialog :visible.sync="dialogVisible">
            <img
              width="100%"
              :src="company.dialogImageUrl"
              alt=""
            >
          </el-dialog>
        </el-form-item>
        <div style="display:inline-block;margin-left:-20px;color:#999999;">仅支持小于1Mb的jpg或png图片格式</div>
      </el-form>
      <div class="next">
        <el-button
          type="primary"
          size="small"
          class="registerBtn"
          @click="registerNext('company')"
        >下一步
        </el-button>
      </div>
    </div>
    <div
      v-show="nextshow"
      style="margin-top:20px"
    >
      <h2>企业注册</h2>
      <div class="titleText">（管理员信息登记）</div>
      <el-form
        :label-position="labelPosition"
        label-width="160px"
        :model="manager"
        :rules="managerRules"
        ref="manager"
      >
        <el-form-item
          label="用户名："
          prop="userName"
        >
          <el-input
            placeholder="6~20位字符组成，以字母开头"
            size="small"
            v-model="manager.userName"
            style="width:80%"
          ></el-input>
        </el-form-item>
        <el-form-item
          label="密码："
          prop="userPassword"
        >
          <el-input
            placeholder="6~20位字符组成，区分大小写"
            size="small"
            :type="see"
            v-model="manager.userPassword"
            style="width:80%"
          >
            <i
              class="el-icon-view"
              slot="suffix"
              style=""
              @click="seePassword"
            ></i></el-input>
        </el-form-item>
        <el-form-item
          label="手机号："
          prop="phone"
        >
          <el-input
            placeholder="11位手机号（仅国内）"
            size="small"
            v-model="manager.phone"
            style="width:80%"
          ></el-input>
        </el-form-item>
        <el-form-item
          label="验证码："
          prop="validate"
        >
          <el-input
            placeholder="短信验证码"
            type="text"
            v-model="manager.validate"
            size="small"
            style="width:40%"
          >
          </el-input>
          <el-button
            type="primary"
            style="width:38%;"
            size="small"
            v-if="!sendMsgDisabled"
            @click="registerSecuritycode"
          >获取验证码</el-button>
          <el-button
            type="primary"
            plain
            style="width:38%;height:40px;"
            v-if="sendMsgDisabled"
          >{{time+'秒后获取'}}</el-button>

        </el-form-item>
        <el-form-item label="">
          <el-checkbox v-model="checked">您已阅读<a
              href=""
              style="text-decoration: none;"
            >《长虹设备云用户注册协议》</a></el-checkbox>
        </el-form-item>
      </el-form>
      <el-button
        type="primary"
        size="small"
        class="registerBtn"
        style="width:30%;height:32px"
        v-on:click="function(){nextshow=!nextshow
           backshow=!backshow}"
      >上一步
      </el-button>
      <el-button
        type="primary"
        size="small"
        class="registerBtn"
        @click="registerInfo('manager')"
        style="width:30%;height:32px"
      >注册
      </el-button>
    </div>
    <div
      class="loginSkip"
      v-on:click="function(){
          isshow=!isshow
          ishide=!ishide
          }"
    >已有账号，直接登录
    </div>
  </div>
</template>

